//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.QuejasMedicas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatSysConfiguracion
    {
        public int CatSysConfiguracionId { get; set; }
        public string Concepto { get; set; }
        public string Descripcion { get; set; }
        public string Valor { get; set; }
        public bool EsAdministrable { get; set; }
        public bool EsActivo { get; set; }
        public string TipoDato { get; set; }
    }
}
