//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.QuejasMedicas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatSysModulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatSysModulo()
        {
            this.CatSysModulo1 = new HashSet<CatSysModulo>();
            this.SysAcceso = new HashSet<SysAcceso>();
        }
    
        public int CatSysModuloId { get; set; }
        public Nullable<int> CatSysModuloPadreId { get; set; }
        public string Concepto { get; set; }
        public string LinkText { get; set; }
        public string ActionName { get; set; }
        public string Icono { get; set; }
        public bool EsActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatSysModulo> CatSysModulo1 { get; set; }
        public virtual CatSysModulo CatSysModulo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysAcceso> SysAcceso { get; set; }
    }
}
