//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.QuejasMedicas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaNoLaborable
    {
        public int DiaNoLaborableId { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool EsActivo { get; set; }
        public string Concepto { get; set; }
        public int TramiteUnidadAtencionId { get; set; }
    
        public virtual TramiteUnidadAtencion TramiteUnidadAtencion { get; set; }
    }
}
