//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.QuejasMedicas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horario()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int HorarioId { get; set; }
        public bool EsActivo { get; set; }
        public int TramiteUnidadAtencionId { get; set; }
        public Nullable<int> CatTipoDiaSemanaId { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public int Capacidad { get; set; }
        public bool EsDiaEspecial { get; set; }
        public Nullable<int> DiaEspecialId { get; set; }
    
        public virtual CatTipoDiaSemana CatTipoDiaSemana { get; set; }
        public virtual DiaEspecial DiaEspecial { get; set; }
        public virtual TramiteUnidadAtencion TramiteUnidadAtencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
