//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.QuejasMedicas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LenguajeCiudadano
    {
        public int LenguajeCiudadanoId { get; set; }
        public string IdTecnico { get; set; }
        public string Region { get; set; }
        public string Descripcion { get; set; }
        public string Concepto { get; set; }
        public bool EsDeVista { get; set; }
        public bool EsActivo { get; set; }
        public bool EsUsuarioInterno { get; set; }
    }
}
