//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.QuejasMedicas.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISSSTEEntities : DbContext
    {
        public ISSSTEEntities()
            : base("name=ISSSTEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CatSysConfiguracion> CatSysConfiguracion { get; set; }
        public virtual DbSet<CatSysModulo> CatSysModulo { get; set; }
        public virtual DbSet<CatSysRol> CatSysRol { get; set; }
        public virtual DbSet<CatTipoDiaSemana> CatTipoDiaSemana { get; set; }
        public virtual DbSet<CatTipoEdoCita> CatTipoEdoCita { get; set; }
        public virtual DbSet<CatTipoEntidad> CatTipoEntidad { get; set; }
        public virtual DbSet<CatTipoInvolucrado> CatTipoInvolucrado { get; set; }
        public virtual DbSet<CatTipoSeccion> CatTipoSeccion { get; set; }
        public virtual DbSet<CatTipoTramite> CatTipoTramite { get; set; }
        public virtual DbSet<DiaEspecial> DiaEspecial { get; set; }
        public virtual DbSet<DiaNoLaborable> DiaNoLaborable { get; set; }
        public virtual DbSet<Domicilio> Domicilio { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Involucrado> Involucrado { get; set; }
        public virtual DbSet<LenguajeCiudadano> LenguajeCiudadano { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Requisito> Requisito { get; set; }
        public virtual DbSet<Seccion> Seccion { get; set; }
        public virtual DbSet<SeccionDetalle> SeccionDetalle { get; set; }
        public virtual DbSet<Solicitud> Solicitud { get; set; }
        public virtual DbSet<SysAcceso> SysAcceso { get; set; }
        public virtual DbSet<TramiteUnidadAtencion> TramiteUnidadAtencion { get; set; }
        public virtual DbSet<UnidadAtencion> UnidadAtencion { get; set; }
        public virtual DbSet<UnidadMedica> UnidadMedica { get; set; }
    }
}
