//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.QuejasMedicas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Involucrado = new HashSet<Involucrado>();
        }
    
        public int PersonaId { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string CURP { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string TelefonoMovil { get; set; }
        public bool EsActivo { get; set; }
        public string Lada { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public bool EsMasculino { get; set; }
        public int Edad { get; set; }
        public Nullable<bool> EsUsuarioBloqueado { get; set; }
        public Nullable<System.DateTime> FechaDesbloqueo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Involucrado> Involucrado { get; set; }
    }
}
