//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.QuejasMedicas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seccion()
        {
            this.SeccionDetalle = new HashSet<SeccionDetalle>();
        }
    
        public int SeccionId { get; set; }
        public bool EsPrimerNivel { get; set; }
        public bool EsActivo { get; set; }
        public int CatTipoSeccionId { get; set; }
        public Nullable<int> Orden { get; set; }
        public int CatTipoTramiteId { get; set; }
    
        public virtual CatTipoSeccion CatTipoSeccion { get; set; }
        public virtual CatTipoTramite CatTipoTramite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeccionDetalle> SeccionDetalle { get; set; }
    }
}
