//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.QuejasMedicas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeccionDetalle
    {
        public int SeccionDetalleId { get; set; }
        public int SeccionId { get; set; }
        public string Contenido { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual Seccion Seccion { get; set; }
    }
}
