//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTE.Tramites2016.QuejasMedicas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadAtencion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnidadAtencion()
        {
            this.TramiteUnidadAtencion = new HashSet<TramiteUnidadAtencion>();
            this.UnidadMedica = new HashSet<UnidadMedica>();
        }
    
        public int UnidadAtencionId { get; set; }
        public string Descripcion { get; set; }
        public bool EsActivo { get; set; }
        public Nullable<int> DomicilioId { get; set; }
        public int CatTipoEntidadId { get; set; }
        public int Contador { get; set; }
        public string Prefijo { get; set; }
        public string Mascara { get; set; }
        public bool ReiniciarContador { get; set; }
    
        public virtual CatTipoEntidad CatTipoEntidad { get; set; }
        public virtual Domicilio Domicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TramiteUnidadAtencion> TramiteUnidadAtencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnidadMedica> UnidadMedica { get; set; }
    }
}
